name: 'Labeler'
description: 'Add labels to new pull requests based on the files that are changed'
author: 'GitHub'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true

runs:
  using: 'composite'
  steps: 
    - run: |
        find . -type d \( -name node_modules -o -name .git \) -prune -false -o -name '*' | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/" > $GITHUB_ACTION_PATH/after.txt
        git fetch --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
        git checkout refs/remotes/origin/${{ github.base_ref }}
        find . -type d \( -name node_modules -o -name .git \) -prune -false -o -name '*' | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/" > $GITHUB_ACTION_PATH/before.txt
        DIFF=$(git --no-pager diff --no-index --unified=6 $GITHUB_ACTION_PATH/before.txt $GITHUB_ACTION_PATH/after.txt || true)
        DIFF="${DIFF//$'\n'/'%0A'}"
        echo "INPUT_DIFF=$DIFF" >> $GITHUB_ENV
      shell: bash
    - run: node $GITHUB_ACTION_PATH/dist/index.js
      env:
        INPUT_REPO-TOKEN: ${{ inputs.repo-token }}
      shell: bash
